# Makefile: A standard Makefile for cpp/main.cpp

CC       = g++
LD       = $(CC)
CPPFLAGS =-g -std=c++17 -Wall -Werror -Wpedantic -Wno-parentheses
#LDFLAGS  = -lstdc++

all  : main
main:main.o
clean:
	/bin/rm -rf main main.o
# END OF FILE
